# Generated by Django 2.2.4 on 2021-01-13 07:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_auto_20210112_1441'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='image',
            field=models.ImageField(blank=True, default='empty.jpeg', upload_to=''),
        ),
    ]
